#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-Assertions
Version  : 1.054
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/B/BB/BBC/Test-Assertions-1.054.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BB/BBC/Test-Assertions-1.054.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtest-assertions-perl/libtest-assertions-perl_1.054-3.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: perl-Test-Assertions-license
Requires: perl-Test-Assertions-man
Requires: perl(Log::Trace)
BuildRequires : perl(Log::Trace)

%description
Test::Assertions v1.054
(c) BBC 2004, 2005. This program is free software; you can redistribute it and/or modify it under the GNU GPL.

%package license
Summary: license components for the perl-Test-Assertions package.
Group: Default

%description license
license components for the perl-Test-Assertions package.


%package man
Summary: man components for the perl-Test-Assertions package.
Group: Default

%description man
man components for the perl-Test-Assertions package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Test-Assertions-1.054
mkdir -p %{_topdir}/BUILD/Test-Assertions-1.054/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Test-Assertions-1.054/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Test-Assertions
cp COPYING %{buildroot}/usr/share/doc/perl-Test-Assertions/COPYING
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Test-Assertions/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Test/Assertions.pm
/usr/lib/perl5/site_perl/5.26.1/Test/Assertions/Manual.pod
/usr/lib/perl5/site_perl/5.26.1/Test/Assertions/TestScript.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Test-Assertions/COPYING
/usr/share/doc/perl-Test-Assertions/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Test::Assertions.3
/usr/share/man/man3/Test::Assertions::Manual.3
/usr/share/man/man3/Test::Assertions::TestScript.3
